language: php

php:
  - 5.3
  - 5.4

before_script:
  - echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

script:
  - vendor/bin/atoum
